version: "3.7"

services:
  my-node-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    labels:
      version: "1.0.0"
    volumes:
      - ./:/app:ro
      - /app/node_modules
